### ISSUE TITLE
synchronizing parallel gateway labels count to number of incoming sequence flows

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js-token-simulation#11]
before actually opening a synchronizing parallel gateway when the last awaited token has just arrived, the "waiting tokens counter" shall show the number of all tokens.

**Comment by nikku** [comment]
I'm closing this issue as I'm not sure what this is about (missing detailed scenario description, steps to reproduce...).

I'm happy to re-open this one if you follow up with some details based on one of our [existing element templates](https://github.com/bpmn-io/bpmn-js-token-simulation/issues/new/choose).
