### ISSUE TITLE
Bump to bpmn-js 9.x.x 

### ISSUE THREAD

**Issue by ps91** [bpmn-io/bpmn-js-token-simulation#115]
__What should we do?__

We need to update token simulation to access the DI trought the utility function `getDi` or trought the element.

__Why should we do it?__

Right now the token simulation doesn't work with the newest version of bpmn-js giving this error:

unhandled error in event listener Error: Tried to access di from the businessObject. The di is available through the diagram element only. For more information, see https://github.com/bpmn-io/bpmn-js/issues/1472

**Comment by adrienCadoret** [comment]
Hey ps91, got the same error..

**Comment by ps91** [comment]
I noticed there's already a commit fixing this. Can you create a version with this fix?

**Comment by nikku** [comment]
Basic support released with [v0.27.0](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/CHANGELOG.md#0270). 

Follow up, so you are aware of current limitations: https://github.com/bpmn-io/bpmn-js-token-simulation/issues/114
