### ISSUE TITLE
Support for History Playback

### ISSUE THREAD

**Issue by HenryHengZJ** [bpmn-io/bpmn-js-token-simulation#116]
Hey this library works really great! I was wondering is there any support for having the tokens simulate or flow through the past history activities/events? If not, is the plugin welcome a PR for that?

**Comment by nikku** [comment]
Please use our existing issue templates; if you're opening a feature request use the template and provide all necessary details.

If you simply have a question you'd like to discuss, please approach us via [our forum](https://forum.bpmn.io/).
