### ISSUE TITLE
Add keyboard shortcuts also to the module for viewer

### ISSUE THREAD

**Issue by nithinssabu** [bpmn-io/bpmn-js-token-simulation#117]
__Is your feature request related to a problem? Please describe__

The token simulation module for the `NavigatedViewer` currently does not support keyboard shortcuts.

__Describe the solution you'd like__

Keyboards shortcuts are also supported in the token simulation module for the viewer.

__Describe alternatives you've considered__

__Additional context__

**Comment by nikku** [comment]
Keyboards shortcuts are a feature available to the [BPMN modeler only](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/Modeler.js#L27), however if that is a feature you desire you can hook it into your app that embeds this library.

**Comment by nikku** [comment]
Closing this as won't fix. If bpmn-js gets support for viewer keyboards shortcuts I'm happy to ship it with the viewer distribution of this library.
