### ISSUE TITLE
Receive Tasks with multiple incoming message flows: Message order should not matter

### ISSUE THREAD

**Issue by timKraeuter** [bpmn-io/bpmn-js-token-simulation#120]
__Describe the Bug__

The order of message arrivals matters for a receive task with two (and probably more) incoming sequence flows.
The following gif shows faulty behavior if a message arrives first from participant 1 (p1).

![buggy_order](https://user-images.githubusercontent.com/21026858/183391900-a4d2c9a8-a2c8-430e-baa8-b6f50d4aba1f.gif)

The message from p1 is "ignored" and has to be sent again after a message from p3 arrives.

If a message from p3 arrives first, there is no problem:

![right_order](https://user-images.githubusercontent.com/21026858/183391918-d8c6cfb0-2146-4140-9759-1fb7c215c34b.gif)

Why do receive tasks behave differently than message catch events? Where is this mentioned in the specification?

![events](https://user-images.githubusercontent.com/21026858/183392123-f68eb9ed-787f-416b-90a8-8ad65a150552.gif)

__Steps to Reproduce__

Load the following model and follow the gif above.
[todo-two-incoming-message-flows-receive-task.txt](https://github.com/bpmn-io/bpmn-js-token-simulation/files/9280614/todo-two-incoming-message-flows-receive-task.txt)

__Expected Behavior__

* [ ] For _blank tasks_ The message order should not matter. Thus, a message from p1 followed by a message from p3 should also result in the termination of the receive task.
* [ ] _Receive tasks_ behave like message catch events and trigger immediately upon receive.

__Describe the alternative you considered__

I think the BPMN specification leans towards a different solution which is less friendly for the purpose of "being a learning tool" (cf. discussion below :arrow_down:):

* Receive tasks behave as message catch events; one incoming message is enough to trigger them.

__Environment__

- Host: Firefox
- OS: Windows 10
- Library version: Currently deployed (0.27.0)

**Comment by nikku** [comment]
@timKraeuter Thanks for opening this issue.

The order of message flows mater because we want to visualize synchronization across processes via messages in strategic process models. While message flows do not have "execution semantics" I've see people encoding order and wait semantics via messages. After all this is a BPMN (also conceptionally) learning tool.

You could argue that we should more closely align to message correlation (where order does not matter) for receive tasks. This is what we do with message receive events.

**Comment by timKraeuter** [comment]
I think you could implement receive tasks similarly to message receive events. But then, one would end up with two different BPMN constructs behaving exactly the same.

Since this does not make much sense for a learning tool, especially when also used for strategic process models, I suggest that messages' order should be irrelevant.
The intended order to receive messages is unclear and not readable from the BPMN model (see my example above). Therefore, in my opinion, if the modeler intends a specific message order, it should be explicitly encoded by chaining message receive tasks/events.

**Comment by nikku** [comment]
> Therefore, in my opinion, if the modeler intends a specific message order, it should be explicitly encoded by chaining message receive tasks/events.

Absolutely agreed. Updated the issue description to reflect this.

**Comment by nikku** [comment]
If you want to [contribute an improvement](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/38bb1b938d1642835b92875e42a7079278fd8eaf/lib/simulator/behaviors/ActivityBehavior.js#L195), please do.

**Comment by rajgoel** [comment]
Hi, in the [BPMN specification](https://www.omg.org/spec/BPMN/2.0.2/PDF) on page 159 it says:

> A Receive Task is a simple Task that is designed to wait for a Message to arrive from an external Participant
(relative to the Process). Once the Message has been received, the Task is completed. 

Thus, I would say that a Receive Task should actually behave like a Catching Message Event. 

For Tasks in general, the spec says:

> A Task is an atomic Activity within a Process flow. A Task is used when the work in the Process **cannot be broken
down** to a finer level of detail. 

If a Task is allowed to receive and send multiple messages, it could be broken down to a finer level of detail. Thus, multiple messages should probably be made explicit (e.g. within a subprocess). Although, I like to conciseness of the current behaviour, the implicit/invisble order (north-east rule?) of messages is difficult to understand based on the spec.

**Comment by nikku** [comment]
The way we model message flows on tasks is explicitly geared towards _strategic process models_. Hence the not 100% spec compliant behavior to resolve messages in diagram write direction top left -> bottom right.

**Comment by nikku** [comment]
I'm fine to give receive tasks message catch behavior, as these are explicitly _not_ intended to live in strategic process models.

**Comment by rajgoel** [comment]
Thanks for the clarification, makes sense to me. In my opinion the following could be reasonably close to the spec:
- `Receive Task` = `Catching Message Event`
- `Send Task` = `Throwing Message Event`
- `Untyped Task` as currently implemented
From a user perspective, an untyped task cannot be broken down as required by the spec. From a modeller perspective almost everything could be broken down to a finer level of detail (so the spec is probably unrealistically strict).

**Comment by nikku** [comment]
@rajgoel This is exactly what's specified in the issue now.
