### ISSUE TITLE
Calling `saveXML` With Token Simulation Active Breaks XML

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-token-simulation#124]
### Describe the Bug

Due to the [`ElementColors`](https://github.com/bpmn-io/bpmn-js-token-simulation/tree/master/lib/features/element-colors) feature the XML is broken when `saveXML` is called with the token simulation active.

* temporary colors are not removed
* colors are set on elements that don't support colors (e.g. `
<bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1" background-color="#fff" border-color="#000">`)

### Steps to Reproduce

1. Activate token simulation
2. Call `saveXML`
3. XML is broken

### Expected Behavior

The XML should not be broken and should look the same independent of the token simulation being active or not.

### Environment

- Library version: 0.30.0

**Comment by marstamm** [comment]
I can reproduce this, moving to backlog

**Comment by philippfromme** [comment]
We could simply disable the token simulation when `saveXML` is called.

Regarding the colors we don't set them correctly (e.g. we set colors on `BPMNPlane` elements). bpmn-js prevents this: https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/cmd/SetColorHandler.js#L87 while the token simulation doesn't.

I guess the most straightforward approach would be:

```javascript
if (is(di, 'color:ColoredEdge')) {
  di.set('border-color', stroke);
} else if (is(di, 'color:ColoredLabel')) {
  di.label && di.label.set('color', stroke);
} else if (is(di, 'color:ColoredShape')) {
  di.set('background-color', fill);
  di.set('border-color', stroke);
}
```

**Comment by nikku** [comment]
> I guess the most straightforward approach would be

I think it is reasonable to simply fix this. It is OK to have colors (as shown) serialized I think.
