### ISSUE TITLE
Support more BPMN elements

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-token-simulation#13]
* [x] Normal Intermediate Event (acts like task)
* [x] Boundary Event
* [ ] ~~Inclusive/Complex Gateway~~
* [x] Collaboration (Pool, Lane, Message Flow)
* [x] Call Activity
* [x] Signal Event
* [ ] Event Subprocess

**Comment by sebwarnke** [comment]
i found several symbols which should just let the token pass.
- service task
- script task

![bildschirmfoto 2017-09-04 um 10 52 41](https://user-images.githubusercontent.com/26740468/30019048-84589180-915f-11e7-9d8a-97ec596a6bf0.png)

**Comment by philippfromme** [comment]
@sebwarnke Expected behavior, but I guess for script and service task it's okay to just let them pass since there is no behavior we could simulate?

**Comment by sebwarnke** [comment]
that's true. service and script simply let the token pass. so the "unsupported" message can be removed easily.

the tasks _message send_, _call activity_ and _collapsed subprocess_ pass the token, too, but invoke a certain behavior simultaneously. 

_message receive_ acts equivalent to message receive event in this case of simulation.

**Comment by philippfromme** [comment]
@sebwarnke , okay, in progress 👍

**Comment by sebwarnke** [comment]
uh, and another thing, that seems to be missing in your top-most list. did we talk on _event subprocesses_? these guys are a very very common concept as well.

**Comment by philippfromme** [comment]
Will add them

**Comment by ashteya** [comment]
I would like to add support for Call Activities to just let the token to pass through (similar to User Task). I can set up a PR for that, or should it do more?

**Comment by philippfromme** [comment]
In the scope of the token simulation a call activity should probably behave like a simple activity. Feel free to add a PR. 👍

**Comment by nikku** [comment]
Closing this issue as too general in favor of https://github.com/bpmn-io/bpmn-js-token-simulation/issues/57 and https://github.com/bpmn-io/bpmn-js-token-simulation/issues/58.
