### ISSUE TITLE
Parallel Join not behaving correctly

### ISSUE THREAD

**Issue by yT0n1** [bpmn-io/bpmn-js-token-simulation#130]
### Describe the Bug

The parallel join does not behave correctly. It waits for the number of tokens equal to the number of incoming sequence flows. However, it does not ensure these are actually coming from all incoming sequence flows. (See gif)

### Steps to Reproduce

See GIF
![parallelJoin](https://user-images.githubusercontent.com/4279289/218479544-db2f7fc8-a999-43f9-a6df-abeba5f0becd.gif)

### Expected Behavior

> The concurrent paths can be joined using a parallel gateway with multiple incoming sequence flows. The process instance waits at the parallel gateway until each incoming sequence is taken.

https://docs.camunda.io/docs/components/modeler/bpmn/parallel-gateways/

I am not sure what the standard says, but I would hope it's the same ;) 

### Environment

Library Version: bpmn-js-token-simulation@0.33.0

**Comment by nikku** [comment]
Thanks for opening this issue. You could check the [BPMN specification](https://www.omg.org/spec/BPMN/2.0/PDF) if you find a trace on parallel join semantics. Once that is confirmed I think it would be a reasonable thing to fix this issue.

**Comment by nikku** [comment]
I guess you verified it is also reproducible against the latest simulator version, [on our demo](https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?pp=1&e=1)?

**Comment by yT0n1** [comment]
I just verified it on the demo. I don't have time to look into the spec, unfortunately. But in Zeebe Play, it works as expected, waiting on all incoming sequence flows.

**Comment by nikku** [comment]
Released via https://github.com/bpmn-io/bpmn-js-token-simulation/releases/tag/v0.34.5.
