### ISSUE TITLE
Exclusive Gateway Throws Error When There Are No Outgoing Elements

### ISSUE THREAD

**Issue by lukagerlach** [bpmn-io/bpmn-js-token-simulation#134]
### Describe the Bug

whenever a process has an exclusive gateway without any outgoing activities and the token simulation reaches the gateway, an error is thrown and the simulation stops working. With every other gateway this does not happen, the simulation finishes as expected.

I believe this comes from lines 41-43 inside the [ExclusiveGatewayBehavior](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/lib/simulator/behaviors/ExclusiveGatewayBehavior.js) class.

### Steps to Reproduce

1. Create model with exclusive gateway that has no following activities.
2. Start token simulation.
3. Simulation throws an error as soon as the token reaches the exclusive gateway.

### Expected Behavior

Like every other gateway, let the simulation finish when it reaches an element with no outgoings

**Comment by nikku** [comment]
@lukagerlach Would you take a stab at fixing the behavior? You'd want to verify this [through a test case](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/test/spec/simulator/SimulatorSpec.js), too.
