### ISSUE TITLE
typed tasks eat tokens

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js-token-simulation#16]
as soon as tasks are switched to typed tasks (e.g. user tasks) the token is consumed in such tasks and does not continue to flowing.

![dkbmlkqrda](https://user-images.githubusercontent.com/26740468/29921031-73cbca92-8e50-11e7-92d7-1e3964c30bc5.gif)

**Comment by philippfromme** [comment]
This has been fixed in v0.5.0. Please download the latest version of the plugin.
