### ISSUE TITLE
Elements Can Be Selected When Token Simulation Active

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-token-simulation#161]
### Describe the Bug

When the token simulation is active elements can still be selected. When disabling the token simulation the context pad remains hidden even though an element is selected.

![brave_gNAHOOY8pG](https://github.com/bpmn-io/bpmn-js-token-simulation/assets/7633572/d0808e3e-bdc2-4d9a-9355-39a056209aa9)

### Steps to Reproduce

1. Activate token simulation
2. Click on an element to select it
3. Disable token simulation
4. Outline is visible but context pad is hidden

### Expected Behavior

Either disable selection completely _or_ fully support it (including outline).

### Environment

- Library version: 33

**Comment by nikku** [comment]
I think there is absolutely a use-case for this one, especially as token-simulation accounts for certain details (such as link names and messages).

Could you assess this bug report against a fully-fledged simulation setup, i.e. https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?pp=1&e=1?

**Comment by philippfromme** [comment]
> I think there is absolutely a use-case for this one, especially as token-simulation accounts for certain details (such as link names and messages).
> 
> Could you assess this bug report against a fully-fledged simulation setup, i.e. https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html?pp=1&e=1?

Can you elaborate? What should happen if I click an element when token simulation? If we want to make selection available during token simulation we have to show the outline as well.

**Comment by nikku** [comment]
If I click on an element it gets focused, and I can check details (i.e. message assignments) on the element, i.e. during a BPMN training session.

![capture RTq7VE_optimized](https://github.com/bpmn-io/bpmn-js-token-simulation/assets/58601/7a805823-82d1-4d5c-afd5-975957b9e248)

Selection is not the primary use case, hence there is no selection outline shown, still, as long as we show the properties panel, we'd need some way to select elements, hence I'm fine with the existing tradeoff (not showing the selection UI, but updating the properties panel with the existing selection).

Given our new (and less intrusive) selection we could, of course, also play with restoring the selection outline. We'd want to evaluate if it adds too much distraction.

**Comment by philippfromme** [comment]
Okay, understood. Selection is a valid use case. I still think if we want to support it we should bring back the outline, maybe in a less prominent form. Otherwise, it looks broken. The context pad not showing on deactivating the token simulation is still a bug that needs fixing.

**Comment by nikku** [comment]
Closing this issue. As discussed it is debatable if it is a `bug` or a `feature`.
