### ISSUE TITLE
More precise simulation log icons.

### ISSUE THREAD

**Issue by timKraeuter** [bpmn-io/bpmn-js-token-simulation#167]
### Describe the solution you'd like

The simulation log currently always shows a default icon for each executed flow node, even if the flow node has a specific type with a more precise icon. See the following example:

![image](https://github.com/bpmn-io/bpmn-js-token-simulation/assets/21026858/6dfd2d45-6d9f-4732-8245-000bdd4215b5)

Here, one could show a receive task icon and event-specific icons for the other events. The icons exist in the BPMN-font and could be used by changing [Log.js](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/main/lib/features/log/Log.js).

If you are interested in this change, I can draft a pull request since I implemented this in my tool based on the token simulation.

Changing to more precise icons can help distinguish two executed flow nodes without names and make the simulation log consistent with the icons in the model.

### Additional context

Currently, it looks like this:
![image](https://github.com/bpmn-io/bpmn-js-token-simulation/assets/21026858/bcd7c604-d991-45ae-949c-e8cfa119646b)
More precise icons would look like this:
![image](https://github.com/bpmn-io/bpmn-js-token-simulation/assets/21026858/8156463f-cbcc-48cb-bab8-f2552d5b9e73)

**Comment by barmac** [comment]
I think this makes sense. Would you like to prepare a pull request with the solution?
