### ISSUE TITLE
Implement catch-all For Error And Escalation Events

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js-token-simulation#184]
### Is your feature request related to a problem? Please describe.

BPMN allows catch-all events for errors and escalations. For instance:

> For an Intermediate Event attached to the boundary of an Activity: If the trigger is an Error, then the errorCode MAY be entered. This Event “catches” the Error. If there is no errorCode, then any error SHALL trigger the Event. If there is an errorCode, then only an Error that matches the errorCode SHALL trigger the Event.

### Describe the solution you'd like

Make catch-all events simulatable. When checking the scope subscriptions, also check if a catch-all subscription is available.

### Describe alternatives you've considered

We could not implement this feature. However, based on the forum, I have the impression that modelers are interested in this behavior in the real engine. They should be able to reproduce the behavior with the simulator.

### Additional context

Camunda 8 implements this feature. Not sure about Camunda 7.
I might provide the implementation if pull requests are welcome.

**Comment by nikku** [comment]
Sounds like a reasonable feature request. Thanks for the hint on C8 support, and the quote from the spec:

![image](https://github.com/user-attachments/assets/4c455021-8eb9-497a-b976-d7876d044963)

Pull requests _are_ welcome. I'm moving this to `backlog` for now.
