### ISSUE TITLE
Make Error Events Bubble Up

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js-token-simulation#187]
### Is your feature request related to a problem? Please describe.

Error End Events trigger nearby event subprocesses or boundary events but they do not bubble up the scope hierarchy.

<details>
<summary>Demo</summary>

![visual-demo](https://github.com/user-attachments/assets/88362a81-c103-4bea-b042-773c6b2297c7)
</details>

### Describe the solution you'd like

Make error events bubble up the same way escalation events do.

<details>
<summary>Demo</summary>

![visual-demo-esc](https://github.com/user-attachments/assets/2e8a16da-0f8f-4de1-b50c-f3c88c7f351f)
</details>

This is backed by the spec, since the hierarchy is explicitly mentioned in the description.

![error-end-event](https://github.com/user-attachments/assets/15fe2168-5ef8-48ec-94ea-dbf3f95b0e4f)

### Describe alternatives you've considered

Not implementing this feature means keeping a mismatch of error and escalation handling. The spec describes both event types almost identically, so a mismatch doesn't seem warranted.

### Additional context

In Camunda 8 both error and escalation events bubble up.
Practically, I don't know about Camunda 7, but the documentation for [_escalation_ events](https://docs.camunda.org/manual/7.17/reference/bpmn20/events/escalation-events/#escalation-intermediate-throw-event) gives a positive hint:
> Like an **error event**, an escalation event is propagated to upper scopes (e.g., from sub-process or call activity) till it is caught.

**Comment by barmac** [comment]
Thanks for the report. I can confirm that the error should indeed be caught by the event subprocess in such situation, and the token simulation does not handle it correctly.
We are happy to merge external contributions, so if you want to provide a PR, we will be happy to review it.

**Comment by nikku** [comment]
@sombrek @barmac I agree on being able to catch it in an error event sub-process. I don't agree on bubbling (cf. mentioned spec text).

An error not caught is undefined behavior, while an escalation is explicitly stated to bubble up in scopes.

**Comment by sombrek** [comment]
@nikku Let's compare the description of both event types.

The description pertaining to bubbling is identical. Escalations lack the terminating effect of errors and the additional error handling in unspecified cases. However, uncaught escalations are unspecified as well.

![escalation-end-event](https://github.com/user-attachments/assets/bf63fc97-ce82-4bd3-8f74-6379f05ab67f)

There's a section specifically talking about events that are propagated.

![propagation-events](https://github.com/user-attachments/assets/62d2585f-bbfa-4899-b439-7a3fb6ed35a6)

Here, the word *innermost* is used with a defining clause (not the innermost scope, but the *innermost which has an attached event*).

I admit it's a close call, but I think if those events weren't bubbling the spec would be much clearer about that.

> An error not caught is undefined behavior, while an escalation is explicitly stated to bubble up in scopes.

What section do you refer to that explicitly states escalations bubble up?

**Comment by barmac** [comment]
Having read the specification fragments on error again, I agree with @sombrek's view on the propagation. There are no special rules for the error propagation. It's specified together with escalation as [in the fragment from page 234 (264 in the PDF) cited above](https://www.omg.org/spec/BPMN/2.0.2/PDF#page=264). 
See also [page 184 (214 in PDF)](https://www.omg.org/spec/BPMN/2.0.2/PDF#page=214):
> Also, Events that are propagated along the hierarchy (errors and escalations) are
propagated from the called element to the Call Activity (and can be handled on its boundary).

IMO both escalations and errors bubble up with the only difference that an escalation does not have to interrupt the flow.

**Comment by sombrek** [comment]
@nikku I'd like to work on this, but based on the conversation I'm not sure if you'd accept a PR. Could you please comment on this? Thanks.

**Comment by barmac** [comment]
From my point of view, the feature request is valid, and we should accept a contribution if it meets our definition of done. So please feel free go ahead with the PR :)

**Comment by nikku** [comment]
Please go ahead and contribute. There is no good reason for errors not to bubble (like escalation does).
