### ISSUE TITLE
subprocesses do not act properly when entered by multiple tokens

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js-token-simulation#20]
### actual behavior
![9y6ln0rwg6](https://user-images.githubusercontent.com/26740468/30030725-e9417038-918e-11e7-93a5-6a5179b8e2bf.gif)

### expected behavior
... see annotations in the model

[subprocessinstances.bpmn.zip](https://github.com/bpmn-io/bpmn-js-token-simulation/files/1274959/subprocessinstances.bpmn.zip)

**Comment by sebwarnke** [comment]
i know... this is difficult. sorry ;)

**Comment by sebwarnke** [comment]
btw, also this behaves wrong already
![fcx5yvef7e](https://user-images.githubusercontent.com/26740468/30031016-fdd68730-918f-11e7-9e21-b0904e219a77.gif)

**Comment by philippfromme** [comment]
Well, that's not good... I have to think about how to fix that...

**Comment by sebwarnke** [comment]
i think this is not a critical problem at this point of the project. you should concentrate on the roadmap first. this is meant to be a reminder

**Comment by philippfromme** [comment]
Yeah, but sometimes it's better to fix this issue first before continuing because it's just gonna become harder to fix.

**Comment by philippfromme** [comment]
Thanks for pointing out all those bugs though. 👍  I'm unaware of a lot of BPMN-specific stuff.

**Comment by philippfromme** [comment]
Closed via 5e0e09c0e5829cba6972a05da187538047955935.
