### ISSUE TITLE
I can change the animation speed

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-token-simulation#22]

**Comment by sebwarnke** [comment]
+1

**Comment by philippfromme** [comment]
Useful for you I guess. Otherwise things might happen to fast to comprehend.

**Comment by sebwarnke** [comment]
#truestory

**Comment by sebwarnke** [comment]
there is another thing about animation speed. passing a very long sequence flow should not consume 10s or more. we might define an upper limit for the token passage from one symbol to its direct successor. this should be a new issue right? let me create it. ;)
