### ISSUE TITLE
Upper Pace Limit for Token Animation

### ISSUE THREAD

**Issue by sebwarnke** [bpmn-io/bpmn-js-token-simulation#24]
To pass a sequence flow between two neighboring  should not last too long.

![jj7q497aer](https://user-images.githubusercontent.com/26740468/30115232-6ae98d1e-931a-11e7-940b-3581772c0cd0.gif)

I do not have a suggestion for a certain limit, yet. It just should be discussed.

**Comment by philippfromme** [comment]
What would be your desired behavior?

**Comment by sebwarnke** [comment]
can we calculate a fixed maximum pace? let's try 5s.

**Comment by philippfromme** [comment]
That's easily possible. We'll have to see if that's actually cool or confusing since the speed then differs depending on the length of connections without a hint why this is. Could also look like it's broken.

**Comment by nikku** [comment]
I'd try out the same speed for all tokens, independent of the edge length, too.

**Comment by philippfromme** [comment]
Closing this for now since no one else complained.

**Comment by nikku** [comment]
:cry:
