### ISSUE TITLE
Event notification when token simulation is triggered

### ISSUE THREAD

**Issue by aminmc** [bpmn-io/bpmn-js-token-simulation#26]
Hi,

Is it possible to register an event listener when someone toggles the simulation button? I would like to hide certain functions when it's triggered.

Thanks

**Comment by philippfromme** [comment]
Yes, the event is called `tokenSimulation.toggleMode`.

Example:

```javascript
modeler.on('tokenSimulation.toggleMode', ({ simulationModeActive }) => {
  if (simulationModeActive) {
    console.log('simulation activated');
  } else {
    console.log('simulation deactivated');
  }
});
```
