### ISSUE TITLE
Blanko end event termintes whole process instance?

### ISSUE THREAD

**Issue by berndruecker** [bpmn-io/bpmn-js-token-simulation#28]
Given the attached process model the first token that reaches the end event termintes the whole instance. This is actually not correct, the second token should continue.

[test.zip](https://github.com/philippfromme/bpmn-js-token-simulation-plugin/files/1927483/test.zip)

![grafik](https://user-images.githubusercontent.com/1217596/38983480-bb9dc1a2-43c4-11e8-976c-b1dd40a2fd1f.png)

**Comment by berndruecker** [comment]
Moved from https://github.com/philippfromme/bpmn-js-token-simulation-plugin/issues/9

**Comment by philippfromme** [comment]
This seems to be a bug in [SimulationState#isFinished](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/lib/features/simulation-state/SimulationState.js#L120).
