### ISSUE TITLE
Error bpmn-js-token-simulation in IE

### ISSUE THREAD

**Issue by ejdomantay** [bpmn-io/bpmn-js-token-simulation#31]
Details of the error below when playing a diagram.

unhandled error in event listener
TypeError: Object doesn’t support property or method ‘includes’

Steps to reproduce:
1. Open BPMN in IE 11
2. Create diagram with simple Start and End event
3. Start "Token Simulation"
4. Click play button in Start Event

See screenshot for detailed console error.
![image](https://user-images.githubusercontent.com/30223320/44762802-e1f3a100-ab7a-11e8-98de-15be212eb126.png)

**Comment by nikku** [comment]
IE :skull:.
