### ISSUE TITLE
Undo, redo, or repeat any actions do not work in Modeler when using  bpmn-js extension for token simulation 

### ISSUE THREAD

**Issue by 1994samaneh** [bpmn-io/bpmn-js-token-simulation#41]
**Expected Behavior**

Could undo, redo, or repeat any actions in Modeler

**Actual Behavior** 

By adding simulation plugging in Modeler;  undo, redo, and repeat  actions would not works correctly anymore. 

**Steps to reproduce the Behavior**

1- Add bpmn-js extension for token simulation 
`https://github.com/bpmn-io/bpmn-js-token-simulation`

2- By adding this in to the code 
`additionalModules: [
    tokenSimulation
  ]`

It would disable undo, redo, and repeat  actions.

Environment

Browser:
Google Chrome,
Firefox,
Opera Web Browser ,
Safari Web Browser,
etc.

OS: Linux,
Windows,
Macintosh, 
Unix,
etc.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-token-simulation/commit/aec385b8df2b427524b719851291195e8709b5f0.

**Comment by nikku** [comment]
Released in `v0.8.1`.
