### ISSUE TITLE
Simulation fails if the model contains lanes

### ISSUE THREAD

**Issue by rudolflippert** [bpmn-io/bpmn-js-token-simulation#44]
Lanes should have no influence on the token simulation. However, if a lane is present in the model, the simulation fails with the message "Lane not supported".

Adding 'bpmn:Lane' to the list of IGNORED_ELEMENTS at line 970 solves this issue for me.

`var IGNORED_ELEMENTS = [ 
  'bpmn:Process',
  'bpmn:Collaboration',
  'bpmn:Lane'
];`

You may want to add this.

**Comment by nikku** [comment]
Fixed in recent library version.
