### ISSUE TITLE
Add support for Boundary Events

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js-token-simulation#45]
**Problem**
When there are `Boundary Events` in the diagram, it's not possible to simulate anything:

<img width="171" alt="screen shot 2018-03-07 at 3 45 48 pm" src="https://user-images.githubusercontent.com/2331533/37074043-bd396ace-221e-11e8-8e03-a432ca4f7754.png">
<img width="398" alt="screen shot 2018-03-07 at 3 41 07 pm" src="https://user-images.githubusercontent.com/2331533/37073957-11c30b00-221e-11e8-97d8-4e2ea021ab84.png">

**Proposal**
Support basic triggering of any boundary events based on:
- [ ] manual trigger

_Optional_
- [ ] pre-set timeout in `ms` (e.g. dropdown on click/hover over a button similar to gateways)

**Comment by nikku** [comment]
Supported in recent versions of the token simulator.
