### ISSUE TITLE
Token vanishes after parallel split

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmn-js-token-simulation#46]
In this process model
<img width="960" alt="parallel-spilt-token-simulation" src="https://user-images.githubusercontent.com/7870843/35867340-cab625f6-0b59-11e8-9b1f-7d72b9fca58e.png">

the token vanishes after the short path is finished.

The second token on the upper path should continue to the end.

**Comment by gcolburn** [comment]
I ran into the same issue and submitted a pull request for review that fixes it for me.

**Comment by philippfromme** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/51
