### ISSUE TITLE
Bump svg.js version to 3.x

### ISSUE THREAD

**Issue by szurilo** [bpmn-io/bpmn-js-token-simulation#48]
Due to an issue (https://github.com/svgdotjs/svg.js/issues/866) in the currently used svg.js we had to use a a locally fixed version of svg.js. Now svg.js v3.x is out there which contains the fix so we can abandon the local fix if you update token-simulation to use svg.js v3.x
Can you guys do that?
Thank you!

**Comment by nikku** [comment]
Happy to take your PR on this one.

Your contribution is needed. We will not act on this any time soon.
