### ISSUE TITLE
simulation stops at intermediate link events

### ISSUE THREAD

**Issue by cwahlmann** [bpmn-io/bpmn-js-token-simulation#60]
__Description__

When using intermediate link events the simulation stops at the throw-event. There is no way to continue.

__Steps to Reproduce__

Create a model using intermediate link events:
![grafik](https://user-images.githubusercontent.com/33593291/108176807-baa23d00-7102-11eb-95ff-f041b0ae39c8.png)

the links-names must be equal
![grafik](https://user-images.githubusercontent.com/33593291/108176835-c130b480-7102-11eb-979f-e9970f445a35.png)

then start the simulation:
![grafik](https://user-images.githubusercontent.com/33593291/108176490-61d2a480-7102-11eb-9057-811f59d2ce7a.png)

the simulation stops at the throw event:
![grafik](https://user-images.githubusercontent.com/33593291/108176567-7adb5580-7102-11eb-898a-b6f18be9ba24.png)
![grafik](https://user-images.githubusercontent.com/33593291/108176625-90507f80-7102-11eb-9728-851ff901b274.png)

__Expected Behavior__

The simulation should recognise link-events and follow them. When there is no corresponding catch-event a message should be logged.

__Environment__

- Host: Camunda modeler 4.4.0 win-x64
- OS: Windows 10
- Library version: 0.11.0

**Comment by nikku** [comment]
Thanks for your feature request.

We simply did not look into this one yet. Moving to backlog, to be picked up some day, maybe.

Contributions welcome.

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/65.
