### ISSUE TITLE
cant change gateway output when inside a subprocess

### ISSUE THREAD

**Issue by cwahlmann** [bpmn-io/bpmn-js-token-simulation#61]
__Describe the Bug__

When the execution is inside a subprocess there is no way to change the gateway-output. The button disappears as soon as the execution enters the subprocess and reappears then leaving it. If theres a loop inside the subprocess, this may end in an endless loop.

__Steps to Reproduce__

Create a model like this:
![grafik](https://user-images.githubusercontent.com/33593291/108181742-92b5d800-7108-11eb-9a4d-a7c5825c7f7c.png)

Activate the simulation, and make sure, the "no"-sequence-flow is active, for we want to see the timer work:
![grafik](https://user-images.githubusercontent.com/33593291/108182065-ec1e0700-7108-11eb-8828-663812d9cc43.png)

Then start the simulation. After the execution entered the subprocess, the gateway-button ist gone.
Now the execution follows the "no"-flow for ever.
![grafik](https://user-images.githubusercontent.com/33593291/108182300-2687a400-7109-11eb-997a-8192aefd23cf.png)

When starting the simulation again and changing the gateway to the "yes"-flow (before button vanishes), you can see, that the button reappears as soon as the execution leaves the subprocess:
![grafik](https://user-images.githubusercontent.com/33593291/108182758-a746a000-7109-11eb-8b22-e2161cf83fa0.png)

__Expected Behavior__

The gateway-button should always be visible to be able to leave such a loop.

__Environment__

- Host: Camunda modeler 4.4.0 win-x64
- OS: Windows 10
- Library version: 0.11.0

**Comment by nikku** [comment]
Will be fixed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/66.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/66.
