### ISSUE TITLE
Token breaks when crossing pools to catch task or event

### ISSUE THREAD

**Issue by avesgroup** [bpmn-io/bpmn-js-token-simulation#79]
https://user-images.githubusercontent.com/7245383/119098036-c16d8280-ba58-11eb-860a-c7500208d518.mp4

When crossing a to another pool, the token stops at a catch task or event, but will continue through if you cross to a start event.
Please see attached video for example.

**Comment by nikku** [comment]
What do you expect this collaboration to do? The second pool won't trigger tasks and catch events, as a process is not started at the time of message arrival.

**Comment by avesgroup** [comment]
Thanks Nikku - my mistake. The BPMN triggers correctly if a start event occurs before the catch.
Thanks

**Comment by nikku** [comment]
No worries.

I guess we could indicate the fact that what you modeled is a token sink so you have a better chance to recognize it.
