### ISSUE TITLE
Token simulation not able to show a livelock

### ISSUE THREAD

**Issue by thoene** [bpmn-io/bpmn-js-token-simulation#89]
__Describe the Bug__

I wanted to use the token flow simulator to demonstrate a simple livelock. But the model is not simulated correctly.

__Steps to Reproduce__

1. start a simulation of the [following model](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/files/7581413/Tokenflussproblem_3.zip): 

    ![Livelockmodel](https://user-images.githubusercontent.com/1507030/142860791-e9274a2e-df06-4711-925e-143bbe283919.jpg)

__Expected Behavior__

Expected: The process does never terminate.
Actual: The token stucks in front of the left parallel gateway.

__Environment__

- OS: e.g. Windows 10
- Library version: 0.13.0

**Comment by nikku** [comment]
Happy to report that things should be happily livelocking again!

![capture BsvSSd_optimized](https://user-images.githubusercontent.com/58601/142919699-1ffa357d-1bb9-4854-aa76-61e6747700a2.gif)

**Comment by nikku** [comment]
Fixed in `bpmn-js-token-simulation-plugin@0.13.1`, too.
