### ISSUE TITLE
Manually trigger user tasks

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn-js-token-simulation#9]
__Problem Description__

The token should wait at user tasks (just like at events) and can be triggered manually to continue.

__Describe the Solution__

* Optionally, any activity may be marked as _pausing_, making incoming tokens halt at it.

**Comment by sebwarnke** [comment]
this is a good idea in general but should be an optional feature. the reason: some users of bpmn might know what user tasks do, generally. and especially in processes dominated by user task this feature would cause a click orgy for them. even though they are only interested in the trivial token flow.

**Comment by philippfromme** [comment]
+1 for Sebastians idea

**Comment by nikku** [comment]
We'll likely add the ability to pause on arbitrary activities (to simulate a bottle neck or simple _wait time_ during task completion) some day, maybe.

**Comment by nikku** [comment]
> We'll likely add the ability to pause on arbitrary activities (to simulate a bottle neck or simple wait time during task completion) some day, maybe.

Baked into the simulator but not supported in the UI yet.

**Comment by nikku** [comment]
A general way to solve this (via a dedicated _pause at node_ behavior) is implemented via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/91).
