### ISSUE TITLE
Set sequence flow when flow is coloured

### ISSUE THREAD

**Issue by johanpza** [bpmn-io/bpmn-js-token-simulation#90]
__Describe the Bug__
Sequence - the colour of the selected flow does not change when it's not the default black. Only greys out when it's black.

__Steps to Reproduce__
1)Add a sequence to your bpmn
2)Add different flows and make them different colours, eg. red, blue and keep one block
3)Start the token simulation
4)Toggle the sequence flow, you will see the black line being greyed out

__Expected Behavior__
The flows/lines should be greyed out to show which one is selected, same as what it's doing when they're the default black colour.
Selected:
![flow1](https://user-images.githubusercontent.com/9568145/130963967-7d51f030-3076-4b5f-9f49-bd68d377d74e.png)
Not selected:
![flow2](https://user-images.githubusercontent.com/9568145/130963960-4a11f6a9-ffd0-4844-addc-da4ed4156f77.png)

__Environment__
- OS: Windows 10
- Library version:0.13.0
- Camunda Modeler: 4.10.0

**Comment by nikku** [comment]
Should be fixed via #93.
