### ISSUE TITLE
Token is away

### ISSUE THREAD

**Issue by michel777777** [bpmn-io/bpmn-js-token-simulation#92]
__Describe the Bug__

The token is disappeared in a task.

__Steps to Reproduce__

1. start the model
2. the token  disappeared

__Expected Behavior__

teh token stay in the task and teh task is waiting for interrupt

__Environment__

[test_interrupt.zip](https://github.com/bpmn-io/bpmn-js-token-simulation/files/7710072/test_interrupt.zip)

https://bpmn-io.github.io/bpmn-js-token-simulation

**Comment by nikku** [comment]
What do you expect and why?

![capture 7Ok6YI_optimized](https://user-images.githubusercontent.com/58601/145984678-7398afcb-07d7-4e91-86eb-a5869bc5ca88.gif)
