### ISSUE TITLE
ReceiveTask behaves like IntermediateCatchEvent but also has ContextPad for Pause

### ISSUE THREAD

**Issue by rajgoel** [bpmn-io/bpmn-js-token-simulation#99]
__Describe the Bug__

A `ReceiveTask` correctly interrupts the token simulation and awaits the user to push the play button. However, the `ReceiveTask` also obtains the context pad for pausing, just like other tasks. This redundant context pad should probably be deactivated, because the simulation will always hold the token and wait for user interaction. 

__Steps to Reproduce__

1. Open https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html
2. Change first task "Insert Card" to a `ReceiveTask`
3. Toggle Token Simulation
4. Toggle Pause-Button of "Insert Card" 
5. Toggle Unpause-Button of "Insert Card" 
6. Toggle Play-Button at Start Event 

__Expected Behavior__

The Pause/Unpause-Buttons should not be shown, because they conflict with the behaviour from `IntermediateCatchEventBehavior.js`. 

__Environment__

- Host (Browser/Node version), if applicable: Firefox/Chrome
- OS: Ubuntu
- Library version: recent

**Comment by rajgoel** [comment]
If

https://github.com/bpmn-io/bpmn-js-token-simulation/blob/ad207df6634b001eaaf8388b65637be84175986c/lib/features/context-pads/handler/PauseHandler.js#L13

is replaced by
```
  if (element.type == 'bpmn:ReceiveTask') {
```
the problem appears to be fixed.

**Comment by nikku** [comment]
Just out of curriosity, does it make sense to you that the receive task behaves like an intermediate catch event? Should it be any different?

**Comment by rajgoel** [comment]
For most models this is a reasonable approximation. However, lets look at the model you posted here: https://twitter.com/i/status/1465401796944437258

If `Activity B` was modelled as a `SendTask` and  `Activity D` was modelled as a `ReceiveTask`, and we have the same message flows (I believe this is not prohibited by the specification), the token flow behaviour of an `IntermediateCatchEvent` does not do what I would expect (i.e. `Activity D` is completed as soon as it receives the first message).

A possible solution could be to have the following behaviour:
- A `ReceiveTask` with (at least) one incoming message flow behaves like any other task
- A `ReceiveTask` without an incoming message flow (in the model) either behaves
   -  like any other task, preferably, with the Pause-behaviour activated by default (the user could turn this off), or
   -  like an `IntermediateCatchEvent`.
